### ISSUE TITLE
Refactor info session times to use ISO-8601 standard

### ISSUE THREAD

**Issue by wesley-dean-gsa** [GSA-TTS/tts.gsa.gov#451]
The info sessions have `date` and `time` fields where `time` looks like:

```
11:30am-1:30pm
```

(that is, two 12-hour times separated by a hyphen) which are then parsed and converted into an internal format.

This is incompatible with ADR #8 which says that all dates and times will be represented internally using ISO-8601 in Eastern time.

Time should be separated into two fields, `start_time` and `end_time` that are ISO-8601-compliant.  In the event that a start or end time does not include a date, internally prefix the date followed by either a `T` (capital letter T) or a space, followed by the time.

Consider the following:

```YAML
- link: "..."
  date: 2024-10-08
  time: 11:30am-12:30pm
```

In the new format, this would look like this:

```YAML
- link: "..."
  date: 2024-10-08
  start_time: 11:30
  end_time: 12:30
```

which, internally, would result in a `start_time` of `2024-10-08 11:30` and an `end time` of `2024-10-08 12:30`

That is, it would be the exact same as:

```YAML
- link: "..."
  date: 2024-10-08
  start_time: 2024-10-08 11:30
  end_time: 2024-10-08 12:30
```

(note: in this case, `date` would be used as a string prefix for when no date is provided with `start_time` or `end_time` and it could be omitted when the times were fully-qualified)
